name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build

      - name: Run gen_csv.sh
        run: |
          cd test
          ./gen_csv.sh

      - name: Run check.sh
        run: |
          cd test
          ./check.sh

      - name: Check exit code
        run: |
          if [ $? -ne 0 ]; then
            echo "Action failed!"
            exit 1
          fi
